# Generated by Django 3.1.3 on 2020-11-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jsonData', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
    ]
